import { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

const translations = {
  en: {
    home: "Home",
    schemes: "Schemes",
    login: "Login",
    register: "Register",
    dashboard: "Dashboard",
    myApplications: "My Applications",
    profile: "Profile",
    localHelp: "Local Help & Support",
    logout: "Logout",
    exploreSchemes: "Explore Schemes",
    createAccount: "Create Citizen Account",
    apply: "Apply",
    viewDetails: "View details",
    lastDate: "Last date",
    officialPortal: "Official Portal",
    heroTitle1: "Empowering Citizens via",
    heroTitle2: "Smart Panchayat",
    heroDesc: "Access government welfare schemes instantly. Apply online, upload documents securely, and track your application progress with complete transparency.",
    needHelp: "Need Help?",
    helpDesc: "If you are facing issues applying online or need offline assistance, our local Panchayat representatives are here to help.",
    tollFree: "Toll-Free Helpline",
    availableTime: "Available 8 AM to 8 PM (Mon-Sat)",
    findLocalSupport: "Find Local Support Centers",
    localHelpTitle: "Find your nearest support center. Our officers and Village Level Entrepreneurs (VLEs) are available to assist you in filling out forms, uploading documents, and tracking your welfare applications.",
    supportDirectory: "Support Centers Directory",
    nodalOfficer: "Nodal Officer",
    beforeYouVisit: "Before You Visit",
    carryAadhaar: "Carry your original Aadhaar Card.",
    bringPassbook: "Bring your active bank passbook.",
    keepMobile: "Keep your registered mobile number active for OTP verification.",
    standardTimings: "Standard Timings",
    mondayFriday: "Monday - Friday:",
    saturday: "Saturday:",
    sunday: "Sunday:",
    closed: "Closed",
    welfareSchemes: "Welfare Schemes",
    browseAndApply: "Browse and apply for government welfare schemes in your panchayat",
    searchSchemes: "Search schemes...",
    allCategories: "All Categories",
    allStatuses: "All Statuses",
    noSchemesFound: "No schemes found",
    tryAdjusting: "Try adjusting your search or filters",
    welcome: "Welcome",
    trackApplications: "Track your welfare scheme applications",
    totalApplications: "Total Applications",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    viewMyApplications: "View My Applications",
    email: "Email",
    password: "Password",
    fullName: "Full Name",
    phone: "Phone Number",
    address: "Address",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    registerHere: "Register here",
    loginHere: "Login here",
    signingIn: "Signing in...",
    signIn: "Sign In",
    submitting: "Submitting...",
    submitApp: "Submit Application",
    uploadDocs: "Upload Documents (PDF, JPG, PNG — max 5 files, 5MB each)",
    reqDocs: "Required documents:",
    applyFor: "Apply for Scheme",
    backToScheme: "Back to scheme",
    backToSchemes: "Back to schemes",
    schemeNotFound: "Scheme not found",
    loading: "Loading...",
  },
  ml: {
    home: "ഹോം",
    schemes: "പദ്ധതികൾ",
    login: "ലോഗിൻ",
    register: "രജിസ്റ്റർ",
    dashboard: "ഡാഷ്ബോർഡ്",
    myApplications: "എന്റെ അപേക്ഷകൾ",
    profile: "പ്രൊഫൈൽ",
    localHelp: "പ്രാദേശിക സഹായം",
    logout: "ലോഗൗട്ട്",
    exploreSchemes: "പദ്ധതികൾ കാണുക",
    createAccount: "അക്കൗണ്ട് സൃഷ്ടിക്കുക",
    apply: "അപേക്ഷിക്കുക",
    viewDetails: "വിശദാംശങ്ങൾ",
    lastDate: "അവസാന തീയതി",
    officialPortal: "ഔദ്യോഗിക പോർട്ടൽ",
    heroTitle1: "പൗരന്മാരെ ശാക്തീകരിക്കുന്നു",
    heroTitle2: "സ്മാർട്ട് പഞ്ചായത്ത് വഴി",
    heroDesc: "സർക്കാർ ക്ഷേമ പദ്ധതികൾ തൽക്ഷണം ആക്‌സസ് ചെയ്യുക. ഓൺലൈനായി അപേക്ഷിക്കുക, രേഖകൾ സുരക്ഷിതമായി അപ്‌ലോഡ് ചെയ്യുക.",
    needHelp: "സഹായം ആവശ്യമുണ്ടോ?",
    helpDesc: "ഓൺലൈനായി അപേക്ഷിക്കാൻ ബുദ്ധിമുട്ടുണ്ടെങ്കിൽ പ്രാദേശിക പ്രതിനിധികൾ നിങ്ങളെ സഹായിക്കുന്നതാണ്.",
    tollFree: "ടോൾ ഫ്രീ ഹെൽപ്പ് ലൈൻ",
    availableTime: "രാവിലെ 8 മുതൽ രാത്രി 8 വരെ",
    findLocalSupport: "പ്രാദേശിക സേവന കേന്ദ്രങ്ങൾ",
    localHelpTitle: "നിങ്ങളുടെ അടുത്തുള്ള സേവന കേന്ദ്രം കണ്ടെത്തുക. അപേക്ഷകൾ പൂരിപ്പിക്കാനും രേഖകൾ അപ്‌ലോഡ് ചെയ്യാനും ഞങ്ങളുടെ ഉദ്യോഗസ്ഥർ സഹായിക്കുന്നതാണ്.",
    supportDirectory: "സേവന കേന്ദ്രങ്ങളുടെ വിവരങ്ങൾ",
    nodalOfficer: "നോഡൽ ഓഫീസർ",
    beforeYouVisit: "സന്ദർശിക്കുന്നതിന് മുമ്പ്",
    carryAadhaar: "നിങ്ങളുടെ ഒറിജിനൽ ആധാർ കാർഡ് കരുതുക.",
    bringPassbook: "നിങ്ങളുടെ ബാങ്ക് പാസ്ബുക്ക് കൊണ്ടുവരിക.",
    keepMobile: "നിങ്ങളുടെ രജിസ്റ്റർ ചെയ്ത മൊബൈൽ നമ്പർ ഒപ്പം കരുതുക.",
    standardTimings: "പ്രവർത്തന സമയം",
    mondayFriday: "തിങ്കൾ - വെള്ളി:",
    saturday: "ശനി:",
    sunday: "ഞായർ:",
    closed: "അവധി",
    welfareSchemes: "ക്ഷേമ പദ്ധതികൾ",
    browseAndApply: "സർക്കാർ ക്ഷേമ പദ്ധതികൾ തിരയുകയും അപേക്ഷിക്കുകയും ചെയ്യുക",
    searchSchemes: "പദ്ധതികൾ തിരയുക...",
    allCategories: "എല്ലാ വിഭാഗങ്ങളും",
    allStatuses: "എല്ലാ അവസ്ഥകളും",
    noSchemesFound: "പദ്ധതികളൊന്നും കണ്ടെത്തിയില്ല",
    tryAdjusting: "നിങ്ങളുടെ തിരയൽ ക്രമീകരിക്കാൻ ശ്രമിക്കുക",
    welcome: "സ്വാഗതം",
    trackApplications: "നിങ്ങളുടെ അപേക്ഷകളുടെ തൽസ്ഥിതി അറിയുക",
    totalApplications: "ആകെ അപേക്ഷകൾ",
    pending: "തീരുമാനമാകാത്തവ",
    approved: "അംഗീകരിച്ചവ",
    rejected: "നിരസിച്ചവ",
    viewMyApplications: "എന്റെ അപേക്ഷകൾ",
    email: "ഇമെയിൽ",
    password: "പാസ്‌വേഡ്",
    fullName: "മുഴുവൻ പേര്",
    phone: "ഫോൺ നമ്പർ",
    address: "വിലാസം",
    dontHaveAccount: "അക്കൗണ്ട് ഇല്ലേ?",
    alreadyHaveAccount: "നിലവിൽ അക്കൗണ്ട് ഉണ്ടോ?",
    registerHere: "ഇവിടെ രജിസ്റ്റർ ചെയ്യുക",
    loginHere: "ഇവിടെ ലോഗിൻ ചെയ്യുക",
    signingIn: "ലോഗിൻ ചെയ്യുന്നു...",
    signIn: "ലോഗിൻ ചെയ്യുക",
    submitting: "സമർപ്പിക്കുന്നു...",
    submitApp: "അപേക്ഷ സമർപ്പിക്കുക",
    uploadDocs: "രേഖകൾ അപ്‌ലോഡ് ചെയ്യുക (PDF, JPG, PNG)",
    reqDocs: "ആവശ്യമായ രേഖകൾ:",
    applyFor: "പദ്ധതിക്ക് അപേക്ഷിക്കുക",
    backToScheme: "പദ്ധതിയിലേക്ക് മടങ്ങുക",
    backToSchemes: "പദ്ധതികളിലേക്ക് മടങ്ങുക",
    schemeNotFound: "പദ്ധതി കണ്ടെത്തിയില്ല",
    loading: "ലഭ്യമാക്കുന്നു...",
  },
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState("en");

  const t = (key) => translations[lang][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
